services:
  database:
    image: postgres:15-alpine
    container_name: leaders_db
    restart: always
    environment:
      POSTGRES_DB: leaders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend  # On précise le dossier du backend
      dockerfile: Dockerfile
    container_name: leaders_backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/leaders_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend # On précise le dossier du frontend
      dockerfile: Dockerfile
    container_name: leaders_frontend
    ports:
      - "8081:80"  # Ton PC (8081) -> Docker (80 interne)
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: