services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: leaders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    # Pas besoin de ports ici pour Railway, la comm est interne

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8085:8080" # On utilise 8085 pour le backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/leaders_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # On utilise 5173 pour le frontend
    environment:
      # L'URL sera à mettre à jour une fois le domaine backend généré
      - VITE_API_URL=https://ton-backend.up.railway.app
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
